name: Deploy to CyberPanel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mitrajayaraya-nextjs:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USER }}
          password: ${{ secrets.REMOTE_SSH_PW }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/mitrajayaraya-nextjs:latest
            docker stop mitrajayaraya-nextjs || true
            docker rm mitrajayaraya-nextjs || true
            docker run -d --name mitrajayaraya-nextjs -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/mitrajayaraya-nextjs:latest
