name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main  # Ganti sesuai branch-mu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".next,public,package.json,package-lock.json,ecosystem.config.js"
          target: ${{ secrets.VPS_TARGET_DIR }}

      - name: Run remote commands (PM2 restart)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.VPS_TARGET_DIR }}
            npm install --omit=dev
            pm2 restart next-app || pm2 start npm --name "next-app" -- start
            pm2 save
